name: Base Ci
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build-and-run-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Download all the code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependendies
        run: |
          pip install -e .

      - name: Run tests
        run: pytest tests -v
