name: Base Ci
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  run-basic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install all packages
        run: pip install -e .

      - name: Run all tests
        run: pytest tests -v
